### ISSUE TITLE
Clicking on "Integrate IRMA" ignores i18n and puts me back in Dutch 

### ISSUE THREAD

**Issue by jlengrand** [privacybydesign/irma-website#11]
I have the locale set to English on https://irma.app/.

I click on "Integrate Irma". I am redirected to https://irma.app/irma-start/. 
All texts are now in Dutch. 

I would expect them in English, still :)

**Comment by synaptic-cleft** [comment]
Oh great, I had never noticed that we're lacking translations there. Thank you for letting us know!

A dedicated IRMA communications person will be working a new (or at least improved) IRMA web presence and this project will be migrated and merged there. We will therefore probably not fix the translation in this project anymore but incorporate your feedback in the new version directly.

I will therefore close your issue here as it will not be fixed in this GitHub project.
